obj-$(CONFIG_TEST_MISC_DEVICE_DRV)		+= 00_misc_device_drv/
obj-$(CONFIG_TEST_CHRDEV)				+= 01_chrdev/
obj-$(CONFIG_TEST_PLATFORM_LED)			+= 02_platform_led_drv/


obj-$(CONFIG_ALL_TEST_DRIVER)			+= test_drv/

